name: "Build and Push to Docker Hub ğŸ³"
run-name: ${{ github.actor }} - ${{ github.event_name }}

on:
  push:
    branches: ["dev"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: check repository out ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Build Docker Image ğŸ—ï¸
        run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/price-fetcher .

      - name: Login to Docker Hub ğŸ³
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub ğŸš€
        run: docker push ${{ vars.DOCKERHUB_USERNAME }}/price-fetcher

      - name: Logout from Docker Hub ğŸšª
        run: docker logout
